/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Grafico.Cliente;

import Clases.DatosEnviados;
import Clases.Vehiculos.Vehiculo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lobje
 */
public class PanelRentar extends javax.swing.JPanel {
    private DatosEnviados datosEnviados;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form PanelRentar
     */
    public PanelRentar() {
        initComponents();
    }

    /* **********************************************************************
     * ******************** METODO QUE RECIBE LAS LISTAS ********************
     * ********************************************************************** */
    public void recibirDatos(DatosEnviados datosEnviados){
        this.datosEnviados = datosEnviados;
        llenarTabla();
    }

    /* **********************************************************************
     * ********************** TABLA PARA MOSTRAR DATOS **********************
     * ********************************************************************** */
    public void llenarTabla(){
        this.modeloTabla = new DefaultTableModel();
        agregarEncabezado();
        int tam = this.datosEnviados.cantidadVehiculos();
        
        Vehiculo v;
        for (int i = 0; i < tam; i++) {
            v = this.datosEnviados.getVehiculos(i);
            if(v.isDisponible())agregaFila(i+1, v.getMarca(), v.getLinea(), v.getModelo(), v.getPlaca(), v.getCostoDia());
        }
        
        this.tablaVehiculos.setModel(modeloTabla);        
    }
    
    private void agregarEncabezado(){
        this.modeloTabla.addColumn("No.");
        this.modeloTabla.addColumn("Marca");
        this.modeloTabla.addColumn("Modelo");
        this.modeloTabla.addColumn("Linea");
        this.modeloTabla.addColumn("Placa");
        this.modeloTabla.addColumn("Costo por dia");
    }
    
    private void agregaFila(int no, String marca, String linea, int modelo, String placa, int costo){
        this.modeloTabla.addRow(new Object[]{dato(no), marca, linea, dato(modelo), placa, dato(costo)});
        this.tablaVehiculos.setModel(modeloTabla);
    }
    
    private String dato(int val){
        return String.valueOf(val);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btRentar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 102));

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaVehiculos);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setText("ID");

        txtId.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        btRentar.setBackground(new java.awt.Color(0, 102, 0));
        btRentar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btRentar.setForeground(new java.awt.Color(255, 255, 255));
        btRentar.setText("Rentar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRentar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRentar)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
