/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafico;

import Hilos.HiloX;
import Hilos.HiloO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author lobje
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private int contador;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.contador = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        x3 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        x4 = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        x5 = new javax.swing.JLabel();
        o5 = new javax.swing.JLabel();
        o4 = new javax.swing.JLabel();
        o3 = new javax.swing.JLabel();
        o2 = new javax.swing.JLabel();
        o1 = new javax.swing.JLabel();
        posicion01 = new javax.swing.JButton();
        posicion02 = new javax.swing.JButton();
        posicion00 = new javax.swing.JButton();
        posicion11 = new javax.swing.JButton();
        posicion12 = new javax.swing.JButton();
        posicion10 = new javax.swing.JButton();
        posicion22 = new javax.swing.JButton();
        posicion21 = new javax.swing.JButton();
        posicion20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        x3.setBackground(new java.awt.Color(0, 0, 102));
        x3.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        x3.setForeground(new java.awt.Color(255, 255, 255));
        x3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x3.setText("x");

        x2.setBackground(new java.awt.Color(0, 0, 102));
        x2.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        x2.setForeground(new java.awt.Color(255, 255, 255));
        x2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x2.setText("x");

        x4.setBackground(new java.awt.Color(0, 0, 102));
        x4.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        x4.setForeground(new java.awt.Color(255, 255, 255));
        x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x4.setText("x");

        x1.setBackground(new java.awt.Color(0, 0, 102));
        x1.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        x1.setForeground(new java.awt.Color(255, 255, 255));
        x1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x1.setText("x");

        x5.setBackground(new java.awt.Color(0, 0, 102));
        x5.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        x5.setForeground(new java.awt.Color(255, 255, 255));
        x5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x5.setText("x");

        o5.setBackground(new java.awt.Color(0, 0, 102));
        o5.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        o5.setForeground(new java.awt.Color(255, 255, 255));
        o5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o5.setText("o");

        o4.setBackground(new java.awt.Color(0, 0, 102));
        o4.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        o4.setForeground(new java.awt.Color(255, 255, 255));
        o4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o4.setText("o");

        o3.setBackground(new java.awt.Color(0, 0, 102));
        o3.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        o3.setForeground(new java.awt.Color(255, 255, 255));
        o3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o3.setText("o");

        o2.setBackground(new java.awt.Color(0, 0, 102));
        o2.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        o2.setForeground(new java.awt.Color(255, 255, 255));
        o2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o2.setText("o");

        o1.setBackground(new java.awt.Color(0, 0, 102));
        o1.setFont(new java.awt.Font("Times New Roman", 3, 150)); // NOI18N
        o1.setForeground(new java.awt.Color(255, 255, 255));
        o1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o1.setText("o");

        posicion01.setText("jButton1");
        posicion01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion01ActionPerformed(evt);
            }
        });

        posicion02.setText("jButton1");
        posicion02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion02ActionPerformed(evt);
            }
        });

        posicion00.setText("jButton1");
        posicion00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion00ActionPerformed(evt);
            }
        });

        posicion11.setText("jButton1");
        posicion11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion11ActionPerformed(evt);
            }
        });

        posicion12.setText("jButton1");
        posicion12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion12ActionPerformed(evt);
            }
        });

        posicion10.setText("jButton1");
        posicion10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion10ActionPerformed(evt);
            }
        });

        posicion22.setText("jButton1");
        posicion22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion22ActionPerformed(evt);
            }
        });

        posicion21.setText("jButton1");
        posicion21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion21ActionPerformed(evt);
            }
        });

        posicion20.setText("jButton1");
        posicion20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(posicion00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(posicion01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(posicion02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(posicion20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(150, 150, 150)
                                        .addComponent(posicion10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(posicion11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(posicion12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(posicion21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(posicion22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(posicion01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(posicion02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(posicion00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(posicion12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(posicion11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(posicion10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(posicion20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(posicion21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(posicion22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posicion00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion00ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion00.getX();
        int yf = this.posicion00.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion00ActionPerformed

    private void posicion01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion01ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion01.getX();
        int yf = this.posicion01.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion01ActionPerformed

    private void posicion02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion02ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion02.getX();
        int yf = this.posicion02.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion02ActionPerformed

    private void posicion10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion10ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion10.getX();
        int yf = this.posicion10.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion10ActionPerformed

    private void posicion11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion11ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion11.getX();
        int yf = this.posicion11.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion11ActionPerformed

    private void posicion12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion12ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion12.getX();
        int yf = this.posicion12.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion12ActionPerformed

    private void posicion20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion20ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion20.getX();
        int yf = this.posicion20.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion20ActionPerformed

    private void posicion21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion21ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion21.getX();
        int yf = this.posicion21.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion21ActionPerformed

    private void posicion22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion22ActionPerformed
        // TODO add your handling code here:
        int xf = this.posicion22.getX();
        int yf = this.posicion22.getY();
        realizarMovimiento(xf, yf);
    }//GEN-LAST:event_posicion22ActionPerformed

    private void realizarMovimiento(int xf, int yf){
        if(contador<10){
            contador++;
            System.out.println("Contador: "+contador);
            JLabel actual = getFicha();
            
            if((contador%2)!=0){
                HiloX h = new HiloX(actual, 25, 10, xf, 10, yf);
                h.start();
            }
            else{
                HiloO h = new HiloO(actual, 25,740, xf, 10, yf);
                h.start();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Limite alcanzado");
        }
    }
    
    private JLabel getFicha(){
        return switch (contador) {
            case 1 -> x1;
            case 2 -> o1;
            case 3 -> x2;
            case 4 -> o2;
            case 5 -> x3;
            case 6 -> o3;
            case 7 -> x4;
            case 8 -> o4;
            case 9 -> x5;
            default -> o5;
        };
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel o1;
    private javax.swing.JLabel o2;
    private javax.swing.JLabel o3;
    private javax.swing.JLabel o4;
    private javax.swing.JLabel o5;
    private javax.swing.JButton posicion00;
    private javax.swing.JButton posicion01;
    private javax.swing.JButton posicion02;
    private javax.swing.JButton posicion10;
    private javax.swing.JButton posicion11;
    private javax.swing.JButton posicion12;
    private javax.swing.JButton posicion20;
    private javax.swing.JButton posicion21;
    private javax.swing.JButton posicion22;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel x3;
    private javax.swing.JLabel x4;
    private javax.swing.JLabel x5;
    // End of variables declaration//GEN-END:variables
}
