/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Grafico;

/**
 *
 * @author lobje
 */
public class Temp extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Temp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHoras = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSegundos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 51));
        setForeground(new java.awt.Color(255, 255, 255));

        txtHoras.setBackground(new java.awt.Color(0, 0, 51));
        txtHoras.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtHoras.setForeground(new java.awt.Color(255, 255, 255));
        txtHoras.setText("00");

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(":");

        txtMinutos.setBackground(new java.awt.Color(0, 0, 51));
        txtMinutos.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtMinutos.setForeground(new java.awt.Color(255, 255, 255));
        txtMinutos.setText("00");

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(":");

        txtSegundos.setBackground(new java.awt.Color(0, 0, 51));
        txtSegundos.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtSegundos.setForeground(new java.awt.Color(255, 255, 255));
        txtSegundos.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMinutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSegundos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMinutos)
                    .addComponent(jLabel4)
                    .addComponent(txtSegundos)
                    .addComponent(txtHoras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel txtHoras;
    public javax.swing.JLabel txtMinutos;
    public javax.swing.JLabel txtSegundos;
    // End of variables declaration//GEN-END:variables
}
