/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico.Admin;

import Clases.DatosEnviados;
import Clases.Vehiculos.DataSetGrafica;
import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.*;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author lobje
 */
public class PanelGraficaPie extends javax.swing.JPanel {
    DatosEnviados datosEnviados;
    DefaultPieDataset datos;
    DataSetGrafica dg;
    int total;
    /**
     * Creates new form PanelGraficaPie
     */
    public PanelGraficaPie() {
        initComponents();
    }

    /* **********************************************************************
     * ******************** METODO QUE RECIBE LAS LISTAS ********************
     * ********************************************************************** */
    public void recibirDatos(DatosEnviados datosEnviados){
        this.datosEnviados = datosEnviados;
    }

    /* **********************************************************************
     * ******************** METODO PARA CREAR LA GRAFICA ********************
     * ********************************************************************** */
    private void generarGrafica(){
        this.panelGrafica.removeAll();
        this.total = datosEnviados.listVehiculos.canticad();
        
        datos = new DefaultPieDataset();
        dg = new DataSetGrafica(this.datosEnviados.listVehiculos);
        dg.calcularDatos();
        
        int cantidad = dg.cantidad();
        for (int i = 0; i < cantidad; i++) {
            agregarDatos(String.valueOf(dg.getVal(i).modelo), dg.getVal(i).getPorcentaje(total));
        }
        
        JFreeChart c = ChartFactory.createPieChart(
                "Grafica de Pie de Modelos de vehiculos",
                datos,
                true,
                true,
                false);
        ChartPanel p = new ChartPanel(c);
        p.setMouseWheelEnabled(true);
        p.setPreferredSize(new Dimension(300, 350));
        
        this.panelGrafica.setLayout(new BorderLayout());
        this.panelGrafica.add(p, BorderLayout.NORTH);
        this.panelGrafica.repaint();
    }
    
    private void agregarDatos(String nombre, int porcentaje){
        datos.setValue(nombre, porcentaje);
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGrafica = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        generarGrafica();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JPanel panelGrafica;
    // End of variables declaration//GEN-END:variables
}
