/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico.Admin;

import Clases.DatosEnviados;
import Grafico.Principal;

/**
 *
 * @author lobje
 */
public class PrincipalAdmin extends javax.swing.JFrame {

    private DatosEnviados datosEnviados;
    /* Paneles */
    private PanelDescuentos panelDescuento;
    private PanelVehiculos panelVehiculos;
    private PanelGraficaPie panelGrafica;
    private PanelGraficaBarras panelGraficaBarras;
    
    private int widthPanel;
    private int heightPanel;
    private int widthTab;
    private int heightTab;
    /**
     * Creates new form PrincipalAdmin
     */
    public PrincipalAdmin() {
        initComponents();
        this.widthPanel = 750;
        this.heightPanel = 500;
        this.widthTab = this.widthPanel + 30;
        this.heightTab = this.heightPanel + 50;
    }
    
    public void recibirDatos(DatosEnviados datosEnviados){
        this.datosEnviados = datosEnviados;
        agregarPaneles();
    }
    
    /* ************************************************************
       ************************************************************ */
    private void agregarPaneles(){
        this.panelDescuento = new PanelDescuentos();
        this.panelDescuento.setVisible(true);
        this.panelDescuento.setSize(widthPanel, heightPanel);
        this.panelDescuento.recibirDatos(datosEnviados);
        
        this.panelVehiculos = new PanelVehiculos();
        this.panelVehiculos.setVisible(true);
        this.panelVehiculos.setSize(widthPanel, heightPanel);
        this.panelVehiculos.recibirDatos(datosEnviados);
        
        this.panelGrafica = new PanelGraficaPie();
        this.panelGrafica.setVisible(true);
        this.panelGrafica.setSize(widthPanel, heightPanel);
        this.panelGrafica.recibirDatos(datosEnviados);
        
        this.panelGraficaBarras = new PanelGraficaBarras();
        this.panelGraficaBarras.setVisible(true);
        this.panelGraficaBarras.setSize(widthPanel, heightPanel);
        this.panelGraficaBarras.recibirDatos(datosEnviados);
        
        this.tabAdmin.addTab("Descuentos", this.panelDescuento);
        this.tabAdmin.addTab("Vehiculos", this.panelVehiculos);
        this.tabAdmin.addTab("Grafica Pie", this.panelGrafica);
        this.tabAdmin.addTab("Grafica Barras", this.panelGraficaBarras);
        
        this.tabAdmin.setSize(widthPanel, heightPanel);
        this.jPanel1.setSize(widthTab, heightTab);
        this.setSize(widthTab, heightTab);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabAdmin = new javax.swing.JTabbedPane();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 102));
        setLocation(new java.awt.Point(300, 100));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrados");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 347, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(261, 261, 261)
                        .addComponent(btnSalir))
                    .addComponent(tabAdmin))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(tabAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Principal login = new Principal();
        login.setVisible(true);
        login.recibirDatos(datosEnviados);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    
    
    
    /* ************************************************************
       ************************************************************ */
    
    /* ************************************************************
       ************************************************************ */
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabAdmin;
    // End of variables declaration//GEN-END:variables
}
